apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: visdom
  namespace: default
spec:
  commonName: visdom.foldy.dev
  secretName: visdom-cert
  dnsNames:
    - visdom.foldy.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer